name: tests

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['latest']
        os: [ubuntu-latest]
        task: [
          '1', '3', '4', '5', '6', '7',
          '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
          '23', '24', '26', '27', '28', '29', '30'
        ]
    name: task ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: runhaskell homework/${{ matrix.task }}.hs
