name: Haskell CI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.3']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        task: ['1', '3', '4']
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }} -- task ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: runhaskell homework/${{ matrix.task }}.hs
