name: Haskell CI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['latest']
        os: [ubuntu-latest, macOS-latest]
        task: ['1', '3', '4', '5', '6', '7', '9', '10', '11', '12', '13', '14', '15', '16', '21']
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }} -- task ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: runhaskell homework/${{ matrix.task }}.hs
